/**
 * auto_generate_document — Edge function that generates a complete BRS document
 * server-side using RAG + LLM, builds a DOCX, and uploads to Supabase Storage.
 *
 * Streams SSE progress events so the frontend can show real-time status.
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import "https://deno.land/x/xhr@0.1.0/mod.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.38.0'
import { getLlmConfig, getEmbeddingConfig, getRagConfig } from '../_shared/llmConfig.ts'
import { performRag } from '../_shared/ragHelper.ts'
import { buildAutoGeneratePrompt, type SectionContext } from '../_shared/promptBuilder.ts'
import { BRS_SERVER_STRUCTURE, type ServerDocSection } from '../_shared/brsStructure.ts'
import { buildAutoGeneratedDocx } from '../_shared/docxServerBuilder.ts'
import { buildFromTemplate } from '../_shared/docxTemplateBuilder.ts'
import { BRS_MD_TEXT_EXAMPLE, BRS_MD_TABLE_EXAMPLE } from '../_shared/brsExamples.ts'

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

/** Call LLM (non-streaming) and return the full text response. */
async function callLlm(
    messages: { role: string; content: string }[],
    llmConfig: { baseUrl: string; apiKey: string; model: string },
    temperature = 0.3,
    maxTokens = 2500,
): Promise<string> {
    const res = await fetch(`${llmConfig.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${llmConfig.apiKey}`,
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            model: llmConfig.model,
            messages,
            temperature,
            max_tokens: maxTokens,
            stream: false,
        }),
    })

    if (!res.ok) {
        const err = await res.text()
        throw new Error(`LLM error (${res.status}): ${err}`)
    }

    const data = await res.json()
    return data.choices?.[0]?.message?.content || ''
}

serve(async (req) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        const {
            projectId,
            docType = 'BRS',
            selectedDocumentPaths,
            projectName = 'Untitled Project',
            docTitle = 'Spesifikasi Keperluan Bisnes (BRS)',
        }: {
            projectId: string
            docType?: string
            selectedDocumentPaths?: string[]
            projectName?: string
            docTitle?: string
        } = await req.json()

        if (!projectId) {
            throw new Error('Missing required field: projectId')
        }

        const supabaseAdmin = createClient(
            Deno.env.get('SUPABASE_URL') ?? '',
            Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
        )

        const llmConfig = getLlmConfig()
        const embeddingConfig = getEmbeddingConfig()
        const ragConfig = getRagConfig()

        if (!llmConfig.apiKey) {
            throw new Error('No LLM API key configured (set LLM_API_KEY or OPENAI_API_KEY)')
        }

        // ── Select structure ─────────────────────────────────────────────────
        const structure = BRS_SERVER_STRUCTURE
        const generatableSections = structure.filter(s => s.autoGenerate)
        const allSectionTitles = structure.map(s => s.title)
        const totalSections = generatableSections.length

        // ── SSE stream setup ─────────────────────────────────────────────────
        const encoder = new TextEncoder()
        const { readable, writable } = new TransformStream<Uint8Array, Uint8Array>()
        const writer = writable.getWriter()

        function sendEvent(data: Record<string, unknown>) {
            writer.write(encoder.encode(`data: ${JSON.stringify(data)}\n\n`)).catch(() => {})
        }

        // ── Background generation pipeline ──────────────────────────────────
        ;(async () => {
            const generatedContent = new Map<string, string>()
            let current = 0

            try {
                for (const section of generatableSections) {
                    current++

                    // Check for client disconnect
                    if (req.signal.aborted) {
                        console.log('Client disconnected, stopping generation')
                        break
                    }

                    sendEvent({
                        type: 'progress',
                        current,
                        total: totalSections,
                        section: section.title,
                        status: 'Mencari dokumen berkaitan...',
                    })

                    try {
                        // ── RAG ──────────────────────────────────────────────
                        const templateInstructions = section.instructions.join(' ').slice(0, 800)
                        const parentSection = findParentSection(section, structure)

                        const ragResult = await performRag(
                            section.title,
                            templateInstructions,
                            parentSection,
                            docType,
                            projectId,
                            selectedDocumentPaths,
                            embeddingConfig,
                            ragConfig,
                            supabaseAdmin,
                        )

                        sendEvent({
                            type: 'progress',
                            current,
                            total: totalSections,
                            section: section.title,
                            status: 'Menjana kandungan...',
                        })

                        // ── Build prompt ─────────────────────────────────────
                        const sectionContext: SectionContext = {
                            instructions: section.instructions,
                            expectedFormat: section.expectedFormat,
                            tableSchemas: section.tableSchemas,
                            parentSection,
                        }

                        const fewShotExample = section.expectedFormat === 'table'
                            ? BRS_MD_TABLE_EXAMPLE
                            : BRS_MD_TEXT_EXAMPLE

                        const { messages } = buildAutoGeneratePrompt(
                            docType,
                            section.title,
                            sectionContext,
                            ragResult.contextText,
                            allSectionTitles,
                            fewShotExample,
                        )

                        // ── LLM call ─────────────────────────────────────────
                        const maxTokens = section.expectedFormat === 'table' ? 4000 : 4000
                        const content = await callLlm(messages, llmConfig, 0.3, maxTokens)

                        generatedContent.set(section.title, content)

                        sendEvent({
                            type: 'section_complete',
                            current,
                            total: totalSections,
                            section: section.title,
                        })

                    } catch (sectionError) {
                        console.error(`Section error [${section.title}]:`, sectionError)
                        // Insert placeholder for failed section
                        generatedContent.set(
                            section.title,
                            `[Kandungan gagal dijana. Sila guna panel AI untuk menjana semula bahagian ini.]\n\nRalat: ${sectionError.message || 'Unknown error'}`,
                        )
                        sendEvent({
                            type: 'section_error',
                            current,
                            total: totalSections,
                            section: section.title,
                            error: sectionError.message || 'Unknown error',
                        })
                    }
                }

                // ── Build DOCX ───────────────────────────────────────────────
                sendEvent({
                    type: 'progress',
                    current: totalSections,
                    total: totalSections,
                    section: '',
                    status: 'Membina dokumen DOCX...',
                })

                let docxBytes: Uint8Array

                // Try template-based builder first (preserves exact government template formatting)
                try {
                    const { data: templateData, error: templateError } = await supabaseAdmin.storage
                        .from('documents')
                        .download('templates/BRS.docx')

                    if (templateError || !templateData) {
                        throw new Error(`Template download failed: ${templateError?.message || 'No data'}`)
                    }

                    const templateBytes = new Uint8Array(await templateData.arrayBuffer())
                    docxBytes = await buildFromTemplate(templateBytes, projectName, docTitle, structure, generatedContent)
                    console.log('DOCX built from template successfully')
                } catch (templateBuildError) {
                    // Fallback to from-scratch builder
                    console.warn('Template builder failed, using fallback:', templateBuildError.message)
                    const docxBlob = await buildAutoGeneratedDocx(
                        projectName,
                        docTitle,
                        structure,
                        generatedContent,
                    )
                    docxBytes = new Uint8Array(await docxBlob.arrayBuffer())
                }

                // ── Upload to storage ────────────────────────────────────────
                const docId = `req-${Date.now()}`
                const storagePath = `documents/${projectId}/${docId}/current.docx`
                const documentKey = `${docId}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`

                const { error: uploadError } = await supabaseAdmin.storage
                    .from('documents')
                    .upload(storagePath.replace('documents/', ''), docxBytes, {
                        contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                        upsert: true,
                    })

                if (uploadError) {
                    throw new Error(`Storage upload failed: ${uploadError.message}`)
                }

                const { data: urlData } = supabaseAdmin.storage
                    .from('documents')
                    .getPublicUrl(storagePath.replace('documents/', ''))
                const publicUrl = urlData.publicUrl

                // ── Upsert DB record ─────────────────────────────────────────
                const { error: dbError } = await supabaseAdmin.from('requirement_docs').upsert({
                    id: docId,
                    project_id: projectId,
                    title: docTitle,
                    type: docType,
                    storage_path: storagePath,
                    document_key: documentKey,
                    content: null,
                    status: 'draft',
                    current_version: 1,
                    last_modified: new Date().toISOString(),
                })

                if (dbError) {
                    throw new Error(`DB upsert failed: ${dbError.message}`)
                }

                // ── Done ─────────────────────────────────────────────────────
                sendEvent({
                    type: 'complete',
                    docId,
                    storagePath,
                    documentKey,
                    publicUrl,
                })

            } catch (fatalError) {
                console.error('Fatal auto-generate error:', fatalError)
                sendEvent({
                    type: 'error',
                    message: fatalError.message || 'Auto-generation failed',
                })
            } finally {
                writer.close().catch(() => {})
            }
        })()

        return new Response(readable, {
            headers: {
                ...corsHeaders,
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'X-Accel-Buffering': 'no',
            },
        })

    } catch (error) {
        console.error('Error:', error)
        return new Response(
            JSON.stringify({ error: error.message }),
            { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )
    }
})

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Find the nearest parent section (higher-level heading) for a given section. */
function findParentSection(section: ServerDocSection, structure: ServerDocSection[]): string {
    const idx = structure.indexOf(section)
    for (let i = idx - 1; i >= 0; i--) {
        if (structure[i].level < section.level) {
            return structure[i].title
        }
    }
    return ''
}
