/**
 * auto_generate_document — Edge function that generates a complete BRS document
 * server-side using RAG + LLM, builds a DOCX, and uploads to Supabase Storage.
 *
 * Streams SSE progress events so the frontend can show real-time status.
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import "https://deno.land/x/xhr@0.1.0/mod.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.38.0'
import { getLlmConfig, getLlmConfigForFeature, getEmbeddingConfig, getRagConfig, buildLlmHeaders, buildLlmEndpoint, buildLlmRequestBody, parseLlmResponse } from '../_shared/llmConfig.ts'
import type { LlmConfig } from '../_shared/llmConfig.ts'
import { embedBatch, performRagWithEmbeddings } from '../_shared/ragHelper.ts'
import { markdownToHtml } from '../_shared/markdownToHtml.ts'
import { buildAutoGeneratePrompt, buildDiagramPrompt, type SectionContext } from '../_shared/promptBuilder.ts'
import { BRS_SERVER_STRUCTURE, type ServerDocSection } from '../_shared/brsStructure.ts'
import { buildAutoGeneratedDocx } from '../_shared/docxServerBuilder.ts'
import { buildFromTemplate, type DiagramImage } from '../_shared/docxTemplateBuilder.ts'
import { BRS_MD_TEXT_EXAMPLE, BRS_MD_TABLE_EXAMPLE, BRS_MD_DIAGRAM_EXAMPLE, BRS_MD_ER_EXAMPLE } from '../_shared/brsExamples.ts'
import { sanitizeMermaidCode, renderMermaidToPng } from '../_shared/renderMermaidServer.ts'

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

/** Call LLM (non-streaming) and return the full text response. */
async function callLlm(
    messages: { role: string; content: string }[],
    llmConfig: LlmConfig,
    temperature = 0.3,
    maxTokens = 2500,
    signal?: AbortSignal,
): Promise<string> {
    const res = await fetch(buildLlmEndpoint(llmConfig), {
        method: 'POST',
        headers: buildLlmHeaders(llmConfig),
        body: JSON.stringify(buildLlmRequestBody(messages, llmConfig, {
            temperature,
            maxTokens,
            stream: false,
        })),
        signal,
    })

    if (!res.ok) {
        const err = await res.text()
        throw new Error(`LLM error (${res.status}): ${err}`)
    }

    const data = await res.json()
    return parseLlmResponse(data, llmConfig.provider)
}

serve(async (req) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        const {
            projectId,
            docType = 'BRS',
            selectedDocumentPaths,
            projectName = 'Untitled Project',
            docTitle = 'Spesifikasi Keperluan Bisnes (BRS)',
        }: {
            projectId: string
            docType?: string
            selectedDocumentPaths?: string[]
            projectName?: string
            docTitle?: string
        } = await req.json()

        if (!projectId) {
            throw new Error('Missing required field: projectId')
        }

        // ── Auth: decode JWT to get userId ────────────────────────────────────
        const token = req.headers.get('authorization')?.replace(/^bearer\s+/i, '') ?? ''
        let userId = 'system'
        if (token) {
            try {
                const payload = JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/')))
                userId = payload.sub as string
            } catch { /* non-fatal — falls back to 'system' */ }
        }

        const supabaseAdmin = createClient(
            Deno.env.get('SUPABASE_URL') ?? '',
            Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
        )

        const llmConfig = getLlmConfig()
        const diagramLlmConfig = getLlmConfigForFeature('diagram')
        const embeddingConfig = getEmbeddingConfig()
        const ragConfig = getRagConfig()

        if (!llmConfig.apiKey) {
            throw new Error('No LLM API key configured (set LLM_API_KEY or ANTHROPIC_API_KEY)')
        }

        // ── Select structure ─────────────────────────────────────────────────
        const structure = BRS_SERVER_STRUCTURE
        const generatableSections = structure.filter(s => s.autoGenerate)
        const allSectionTitles = structure.map(s => s.title)
        const totalSections = generatableSections.length
        const totalDiagramSections = generatableSections.filter(s => s.diagramType).length

        // ── SSE stream setup ─────────────────────────────────────────────────
        const encoder = new TextEncoder()
        const { readable, writable } = new TransformStream<Uint8Array, Uint8Array>()
        const writer = writable.getWriter()

        function sendEvent(data: Record<string, unknown>) {
            writer.write(encoder.encode(`data: ${JSON.stringify(data)}\n\n`)).catch((e: Error) => console.debug('SSE write failed:', e.message))
        }

        // SSE keep-alive: send a comment line every 20s so the browser/proxy
        // doesn't drop the connection during silent LLM processing.
        function sendHeartbeat() {
            writer.write(encoder.encode(': keep-alive\n\n')).catch((e: Error) => console.debug('SSE heartbeat failed:', e.message))
        }

        // Concurrency limiter — cap parallel LLM calls to avoid rate-limit stalls.
        const CONCURRENCY = 8
        let running = 0
        const queue: (() => void)[] = []
        function acquireSlot(): Promise<void> {
            if (running < CONCURRENCY) { running++; return Promise.resolve() }
            return new Promise(resolve => queue.push(() => { running++; resolve() }))
        }
        function releaseSlot() {
            running--
            const next = queue.shift()
            if (next) next()
        }

        // ── Background generation pipeline ───────────────────────────────────
        ;(async () => {
            const generatedContent = new Map<string, string>()
            // Collects HTML + sources for section_content table (AI panel awareness)
            const sectionHtmlMap = new Map<string, { html: string; sources: string[]; contentType: string }>()
            // Collects Mermaid code per diagram-eligible section
            const diagramCodes = new Map<string, string>()

            // Keep SSE connection alive throughout the entire generation
            const heartbeat = setInterval(sendHeartbeat, 20_000)

            try {
                // ── Phase 1: Batch-embed all section queries + pre-fetch template ──
                // 40 individual Voyage AI calls → 2 batch calls (one per query variant).
                // Template download overlaps with embedding so it costs nothing extra.
                sendEvent({
                    type: 'progress',
                    current: 0,
                    total: totalSections,
                    section: '',
                    status: 'Preparing document context...',
                })

                const sectionMeta = generatableSections.map(section => ({
                    query1: `Context needed for ${docType} section: ${section.title}.`,
                    query2: `${docType} ${findParentSection(section, structure)} ${section.title} ${section.instructions.join(' ').slice(0, 800)}`,
                    parentSection: findParentSection(section, structure),
                }))

                const [[embeddings1, embeddings2], templateFetch] = await Promise.all([
                    Promise.all([
                        embedBatch(sectionMeta.map(s => s.query1), embeddingConfig),
                        embedBatch(sectionMeta.map(s => s.query2), embeddingConfig),
                    ]),
                    supabaseAdmin.storage.from('documents').download('templates/BRS.docx'),
                ])

                // Pair embeddings per section: sectionEmbeddings[i] = [q1_vec, q2_vec]
                const sectionEmbeddings: [number[], number[]][] =
                    generatableSections.map((_, i) => [embeddings1[i], embeddings2[i]])

                // Allocate docId now so the frontend can poll the DB if SSE drops
                const docId = `req-${Date.now()}`
                const storagePath = `documents/${projectId}/${docId}/current.docx`
                sendEvent({ type: 'started', docId, total: totalSections })

                // ── Phase 2: Vector search + LLM for all sections in parallel ────
                await Promise.all(
                    generatableSections.map(async (section, idx) => {
                        const current = idx + 1

                        if (req.signal.aborted) return

                        sendEvent({
                            type: 'progress',
                            current,
                            total: totalSections,
                            section: section.title,
                            status: 'Searching relevant documents...',
                        })

                        try {
                            // ── RAG (search only — embeddings pre-computed) ───
                            const ragResult = await performRagWithEmbeddings(
                                section.title,
                                sectionEmbeddings[idx],
                                projectId,
                                selectedDocumentPaths,
                                ragConfig,
                                supabaseAdmin,
                            )

                            if (req.signal.aborted) return

                            sendEvent({
                                type: 'progress',
                                current,
                                total: totalSections,
                                section: section.title,
                                status: 'Generating content...',
                            })

                            // ── Build prompt ──────────────────────────────────
                            const sectionContext: SectionContext = {
                                instructions: section.instructions,
                                expectedFormat: section.expectedFormat,
                                tableSchemas: section.tableSchemas,
                                parentSection: sectionMeta[idx].parentSection,
                            }

                            const fewShotExample = section.expectedFormat === 'table'
                                ? BRS_MD_TABLE_EXAMPLE
                                : BRS_MD_TEXT_EXAMPLE

                            const { messages } = buildAutoGeneratePrompt(
                                docType,
                                section.title,
                                sectionContext,
                                ragResult.contextText,
                                allSectionTitles,
                                fewShotExample,
                            )

                            // ── LLM call (throttled) ─────────────────────────
                            const maxTokens = section.expectedFormat === 'table' ? 1500 : 2500
                            await acquireSlot()
                            let content: string
                            try {
                                content = await callLlm(messages, llmConfig, 0.3, maxTokens, req.signal)
                            } finally {
                                releaseSlot()
                            }

                            generatedContent.set(section.title, content)

                            // ── Diagram LLM call (if section has diagramType) ──
                            if (section.diagramType && section.diagramHint && !req.signal.aborted) {
                                try {
                                    sendEvent({
                                        type: 'progress',
                                        current,
                                        total: totalSections,
                                        section: section.title,
                                        status: 'Generating diagram...',
                                    })

                                    const diagramExample = section.diagramType === 'erDiagram'
                                        ? BRS_MD_ER_EXAMPLE
                                        : BRS_MD_DIAGRAM_EXAMPLE

                                    const { messages: diagramMessages } = buildDiagramPrompt(
                                        docType,
                                        section.title,
                                        section.diagramType,
                                        section.diagramHint,
                                        ragResult.contextText,
                                        allSectionTitles,
                                        diagramExample,
                                    )

                                    await acquireSlot()
                                    let mermaidRaw: string
                                    try {
                                        const activeDiagramConfig = section.diagramType !== 'flowchart' ? diagramLlmConfig : llmConfig
                                        mermaidRaw = await callLlm(diagramMessages, activeDiagramConfig, 0.2, 1800, req.signal)
                                    } finally {
                                        releaseSlot()
                                    }

                                    const sanitized = sanitizeMermaidCode(mermaidRaw)
                                    if (sanitized) {
                                        diagramCodes.set(section.title, sanitized)
                                        console.log(`[diagram] Code ready for "${section.title}" (${sanitized.split('\n').length} lines)`)
                                    } else {
                                        console.warn(`[diagram] Invalid Mermaid code for ${section.title} — LLM output did not start with a known diagram type`)
                                        sendEvent({
                                            type: 'diagram_error',
                                            section: section.title,
                                            error: 'Diagram code invalid — skipped',
                                        })
                                    }
                                } catch (diagError) {
                                    console.warn(`[diagram] LLM error for ${section.title}:`, (diagError as Error).message)
                                    sendEvent({
                                        type: 'diagram_error',
                                        section: section.title,
                                        error: (diagError as Error).message || 'Diagram generation failed',
                                    })
                                }
                            }

                            // Store HTML version + sources for AI panel section_content
                            // Include Mermaid code in HTML if diagram was generated
                            const mermaidCode = diagramCodes.get(section.title)
                            const baseHtml = markdownToHtml(content)
                            const fullHtml = mermaidCode
                                ? `${baseHtml}\n<pre class="mermaid">${mermaidCode}</pre>\n<p><strong>Rajah: ${section.title}</strong></p>`
                                : baseHtml

                            sectionHtmlMap.set(section.title, {
                                html: fullHtml,
                                sources: ragResult.sources,
                                contentType: section.expectedFormat === 'table' ? 'table' : 'text',
                            })

                            sendEvent({
                                type: 'section_complete',
                                current,
                                total: totalSections,
                                section: section.title,
                            })

                        } catch (sectionError) {
                            if ((sectionError as Error).name === 'AbortError') return
                            console.error(`Section error [${section.title}]:`, sectionError)
                            generatedContent.set(
                                section.title,
                                `[Kandungan gagal dijana. Sila guna panel AI untuk menjana semula bahagian ini.]\n\nRalat: ${(sectionError as Error).message || 'Unknown error'}`,
                            )
                            sendEvent({
                                type: 'section_error',
                                current,
                                total: totalSections,
                                section: section.title,
                                error: (sectionError as Error).message || 'Unknown error',
                            })
                        }
                    })
                )

                // ── Phase 2.5: Render diagrams to PNG ────────────────────────
                const diagramImages = new Map<string, DiagramImage>()

                console.log(`[diagram] Phase 2 complete — ${diagramCodes.size}/${totalDiagramSections} diagram codes generated`)

                if (diagramCodes.size > 0 && !req.signal.aborted) {
                    sendEvent({
                        type: 'progress',
                        current: totalSections,
                        total: totalSections,
                        section: '',
                        status: `Rendering ${diagramCodes.size} diagram(s) to images...`,
                    })

                    const renderEntries = [...diagramCodes.entries()]
                    const RENDER_BATCH = 4
                    for (let ri = 0; ri < renderEntries.length; ri += RENDER_BATCH) {
                        const batch = renderEntries.slice(ri, ri + RENDER_BATCH)
                        const results = await Promise.all(
                            batch.map(async ([title, code]) => {
                                sendEvent({
                                    type: 'progress',
                                    current: totalSections,
                                    total: totalSections,
                                    section: title,
                                    status: `Rendering diagram for "${title}"...`,
                                })
                                const result = await renderMermaidToPng(code, req.signal)
                                return { title, result }
                            })
                        )
                        for (const { title, result } of results) {
                            if (result) {
                                diagramImages.set(title, result)
                            } else {
                                console.warn(`[diagram] Render failed for "${title}"`)
                                sendEvent({
                                    type: 'diagram_error',
                                    section: title,
                                    error: 'Diagram render failed — section will have text only',
                                })
                            }
                        }
                    }

                    console.log(`[diagram] Phase 2.5 complete — ${diagramImages.size}/${diagramCodes.size} diagrams rendered`)
                    sendEvent({
                        type: 'progress',
                        current: totalSections,
                        total: totalSections,
                        section: '',
                        status: `${diagramImages.size} diagram(s) ready. Building document...`,
                    })
                }

                // If the client disconnected before we reach the build phase
                // (React StrictMode throwaway mount, user Cancel, or an early
                // SSE abort), stop here — do NOT build/upload/upsert. Otherwise
                // every aborted attempt would leave a stray requirement_docs row.
                // A genuine SSE drop *during* Phase 3 happens after this check,
                // so the frontend's polling fallback still recovers that case.
                if (req.signal.aborted) {
                    console.log('[auto-gen] Client disconnected before build — skipping document creation')
                    return
                }

                // ── Phase 3: Build DOCX using pre-fetched template ───────────
                sendEvent({
                    type: 'progress',
                    current: totalSections,
                    total: totalSections,
                    section: '',
                    status: 'Building DOCX document...',
                })

                let docxBytes: Uint8Array

                try {
                    if (templateFetch.error || !templateFetch.data) {
                        throw new Error(`Template download failed: ${templateFetch.error?.message || 'No data'}`)
                    }
                    const templateBytes = new Uint8Array(await templateFetch.data.arrayBuffer())
                    docxBytes = await buildFromTemplate(templateBytes, projectName, docTitle, structure, generatedContent, diagramImages)
                    console.log('DOCX built from template successfully')
                } catch (templateBuildError) {
                    console.warn('Template builder failed, using fallback:', (templateBuildError as Error).message)
                    const docxBlob = await buildAutoGeneratedDocx(
                        projectName,
                        docTitle,
                        structure,
                        generatedContent,
                        diagramImages,
                    )
                    docxBytes = new Uint8Array(await docxBlob.arrayBuffer())
                }

                // ── Upload to storage ────────────────────────────────────────
                const documentKey = `${docId}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`

                const { error: uploadError } = await supabaseAdmin.storage
                    .from('documents')
                    .upload(storagePath.replace('documents/', ''), docxBytes, {
                        contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                        upsert: true,
                    })

                if (uploadError) {
                    throw new Error(`Storage upload failed: ${uploadError.message}`)
                }

                const { data: urlData } = supabaseAdmin.storage
                    .from('documents')
                    .getPublicUrl(storagePath.replace('documents/', ''))
                const publicUrl = urlData.publicUrl

                // ── Upsert DB record ─────────────────────────────────────────
                const { error: dbError } = await supabaseAdmin.from('requirement_docs').upsert({
                    id: docId,
                    project_id: projectId,
                    title: docTitle,
                    type: docType,
                    storage_path: storagePath,
                    document_key: documentKey,
                    content: null,
                    status: 'draft',
                    current_version: 1,
                    last_modified: new Date().toISOString(),
                })

                if (dbError) {
                    throw new Error(`DB upsert failed: ${dbError.message}`)
                }

                // ── Phase 4b: Batch-upsert section content + activity log ────
                if (sectionHtmlMap.size > 0) {
                    const sectionRows = Array.from(sectionHtmlMap.entries()).map(([title, data]) => ({
                        project_id: projectId,
                        doc_id: docId,
                        section_title: title,
                        html: data.html,
                        sources: data.sources,
                        content_type: data.contentType,
                        diagram_type: null,
                        is_in_document: true,
                        created_by: userId,
                        updated_at: new Date().toISOString(),
                    }))
                    const { error: scError } = await supabaseAdmin
                        .from('section_content')
                        .upsert(sectionRows, { onConflict: 'doc_id,section_title' })
                    if (scError) console.error('section_content batch insert error:', scError)

                    // Activity: one entry per generated section
                    const activityRows = Array.from(sectionHtmlMap.entries()).map(([title, data]) => ({
                        project_id: projectId,
                        doc_id: docId,
                        user_id: userId,
                        action: 'section_generated',
                        details: { sectionTitle: title, contentType: data.contentType, source: 'auto_gen' },
                    }))
                    // Activity: doc_created entry
                    activityRows.push({
                        project_id: projectId,
                        doc_id: docId,
                        user_id: userId,
                        action: 'doc_created',
                        details: { docTitle, docType, sectionCount: generatableSections.length },
                    })
                    await supabaseAdmin.from('activity_log').insert(activityRows)
                        .then(({ error }) => { if (error) console.error('activity_log insert error:', error) })
                }

                // ── Done ─────────────────────────────────────────────────────
                sendEvent({
                    type: 'complete',
                    docId,
                    storagePath,
                    documentKey,
                    publicUrl,
                })

            } catch (fatalError) {
                console.error('Fatal auto-generate error:', fatalError)
                sendEvent({
                    type: 'error',
                    message: fatalError.message || 'Auto-generation failed',
                })
            } finally {
                clearInterval(heartbeat)
                writer.close().catch(() => {})
            }
        })()

        return new Response(readable, {
            headers: {
                ...corsHeaders,
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'X-Accel-Buffering': 'no',
            },
        })

    } catch (error) {
        console.error('Error:', error)
        return new Response(
            JSON.stringify({ error: error.message }),
            { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )
    }
})

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Find the nearest parent section (higher-level heading) for a given section. */
function findParentSection(section: ServerDocSection, structure: ServerDocSection[]): string {
    const idx = structure.indexOf(section)
    for (let i = idx - 1; i >= 0; i--) {
        if (structure[i].level < section.level) {
            return structure[i].title
        }
    }
    return ''
}
